### ISSUE TITLE
firehol_webserver blocks "38.0.0.0/8"

### ISSUE THREAD

**Issue by doublex** [firehol/blocklist-ipsets#10]
firehol_webserver -> pushing_inertia_blocklist -> blocks "38.0.0.0/8"
Maybe too many false positives.

**Comment by ktsaou** [comment]
Let's see why:

```sh
# echo "38.0.0.0/8" | iprange - --compare-next /etc/firehol/ipsets/*.{ip,net}set | grep -v ",0$" | cut -d ',' -f 2,8 | ( IFS=","; while read ipset matches; do echo "$matches $ipset"; done ) | sort -n -r | head -n 10

16777216 /etc/firehol/ipsets/pushing_inertia_blocklist.netset
16777216 /etc/firehol/ipsets/firehol_webserver.netset
9308886 /etc/firehol/ipsets/iblocklist_level3.netset
9308886 /etc/firehol/ipsets/ib_bluetack_level3.netset
1263324 /etc/firehol/ipsets/iblocklist_level2.netset
1263324 /etc/firehol/ipsets/ib_bluetack_level2.netset
866284 /etc/firehol/ipsets/sorbs_dul.netset
421319 /etc/firehol/ipsets/iblocklist_level1.netset
421319 /etc/firehol/ipsets/ib_bluetack_level1.netset
65538 /etc/firehol/ipsets/iblocklist_badpeers.netset
```

ok, this is blocked by `pushing_inertia_blocklist` which is included in `firehol_webserver`.

Here is what they say about it:

https://github.com/pushinginertia/ip-blacklist/blob/6d59680b3717f92fc7cb71a8e3e4aae169082a12/ip_blacklist.conf#L346-L347

**Comment by jtkdpu** [comment]
That is unfortunate.  While some portions of that prefix are used for various monitoring, perhaps by Cyveillance, some are most certainly not.  `whois 38.229.0.0` for example.  In that prefix is a lot of Team Cymru services, including some systems supporting Malware Hash Registry (MHR), which is a malware fighting tool presumably many security-conscious organizations would like keep working.

**Comment by ktsaou** [comment]
I have opened issue https://github.com/pushinginertia/ip-blacklist/issues/6 at their repo.

**Comment by doublex** [comment]
Wouldn't it be easier to remove "pushing_inertia_blocklist" from "firehol_webserver"?

**Comment by ktsaou** [comment]
> Wouldn't it be easier to remove "pushing_inertia_blocklist" from "firehol_webserver"?

Yes we could do that. However, I think this list is quite valuable. In all the web server related events I have recently encountered, `pushinginertia` matched more of the attackers than any other list.

Generally speaking, `firehol_webserver` should be applied in a stateful way, at the input (i.e. inbound NEW connections) of a web server. It should not be applied to outbound NEW connections of the web server. Another use could be web server deny rules (which also blocks only inbound NEW connections).

But I agree, that either they will fine tune it, or it has to be removed from `firehol_webserver`.

Let's give them some time...

**Comment by thulle** [comment]
Subnet removed from the list as per 2017-02-13 according to https://github.com/pushinginertia/ip-blacklist/issues/6 

This issue can be closed.
