### ISSUE TITLE
[pushing_inertia_blocklist]: Wrong IP range marked

### ISSUE THREAD

**Issue by vinitraje** [firehol/blocklist-ipsets#119]
There's a problem with pushing inertia blacklist. There's an IP range in pushing inertia blacklist: 54.160.0.0/12 which in the firehol_webserver list is mentioned incorrectly as 54.160.0.0/11.

**Comment by Jas0n99** [comment]
It has just been auto-reduced... Instead of the two in the pushing inertia source:

54.160.0.0/12 = 54.160.0.0 - 54.175.255.255
54.176.0.0/12 = 54.176.0.0 - 54.191.255.255

It is simply the following in the firehol list:

54.160.0.0/11 = 54.160.0.0 - 54.191.255.255

**Comment by vinitraje** [comment]
Oh alright. Thank you. It has some false positives, so I'll just drop the list.
