### ISSUE TITLE
disable ipset list

### ISSUE THREAD

**Issue by YoungVor** [firehol/blocklist-ipsets#14]
First I wanted to say, fantastic feature.  Thank you for all your work to aggregate so many freely available iplists under one easy to use feature!

I was wondering if there was any way to turn off an iplist's auto updates once its enabled?  Something like "update-ipsets disable"?   I couldn't find anything like that in the wiki, and I couldn't find any man page.

**Comment by ktsaou** [comment]
Hi, thanks!

Just delete its `.source` file from `/etc/firehol/ipsets/`.

**Comment by YoungVor** [comment]
Got it.  Thanks!
