### ISSUE TITLE
The Dragon Research Group (DRG) is dead (dragon_*) feeds

### ISSUE THREAD

**Issue by jtkristoff** [firehol/blocklist-ipsets#15]
In case you weren't aware, the dragon_\* feeds are officially dead and are no longer being updated.  Most of the underlying infrastructure responsible for the feed data has been shut down.  The home page remains, but eventually it is expected to go away as well.  The DRG is in a word, dead.

Perhaps you'd keep any old data around for awhile while the dragonresearchgroup.org page is still accessible?  Otherwise, I'd recommend removing references to that project and the data.

I am the former Managing Director.  Horse's mouth here.  :-)  Fortunately there is some good news.  I'll open up a second issue with details.

**Comment by ktsaou** [comment]
I am very sorry. I had the impression team-cymru was supporting DRG.

As long as the feeds can be downloaded, I'll have them at the site. The site does say how old that feeds are (they are 123 days old now). I'll remove them once the downloader starts giving errors.

Thanks for letting me know and I wish everything to go well for you at dataplane.org

**Comment by megahall** [comment]
FYI: these feeds are fully failing for me now in a separate project.

**Comment by ktsaou** [comment]
oops! I forgot to update this ticket. I removed them, a month ago.
