### ISSUE TITLE
DataPlane.org feeds

### ISSUE THREAD

**Issue by jtkdpu** [firehol/blocklist-ipsets#16]
[DataPlane.org](https://dataplane.org) is providing feeds.  Perhaps you'd consider incorporating them into the project?  I am the former managing director of the DRG and have spun up this new independent project, partially modeled on some of the past DRG work I had done.

**Comment by ktsaou** [comment]
I am adding them now...

**Comment by ktsaou** [comment]
I see that each entry in these feeds is a single IPv4. Will this remain like that or you plan to add subnets too?

**Comment by ktsaou** [comment]
added!

**Comment by ktsaou** [comment]
updating the sites now...

**Comment by ktsaou** [comment]
http://iplists.firehol.org/?ipset=dataplane_sipquery
http://iplists.firehol.org/?ipset=dataplane_sshclient
http://iplists.firehol.org/?ipset=dataplane_sshpwauth

I you have any comments, please let know.
Thanks!

**Comment by jtkdpu** [comment]
Note, that an address may be either IPv4 or IPv6.  Although in practice this would be rare for the current set of feeds, it is possible.  In new feeds to come it may be more common.

Currently there are no feeds where the IP address is actually a prefix instead of an individual address, and there are no plans for feeds such as the DRG HTTP scanner feed that did that, but I wouldn't rule it out.

**Comment by ktsaou** [comment]
ok. I would appreciate it if you let me know when and if these conditions change. The code currently filters out whatever not matching single IPv4 IPs.
