### ISSUE TITLE
Request: firehol_webclient IP list

### ISSUE THREAD

**Issue by abelbeck** [firehol/blocklist-ipsets#17]
@ktsaou First I must say the FireHOL IP Lists are a world class gem, simply fantastic work !

I would like to suggest a new "firehol_webclient" IP list, sharing some of the firehol_webserver blocklists, but more designed for outgoing, forwarded traffic from web browsers.

You have stated here:

> Generally speaking, firehol_webserver should be applied in a stateful way, at the input (i.e. inbound NEW connections) of a web server. It should not be applied to outbound NEW connections of the web server. 

A new firehol_webclient list could be applied in the OUTPUT and FORWARD chains protecting web clients, and no harm applied to the INPUT chain as well.

Preventing phishing attacks would be the primary objective, here is a first-cut at a "firehol_webclient" IP list:

```
hphosts_psh
cleanmx_phishing
atlas_phishing_30d
atlas_fastflux_30d
blueliv_crimeserver_last_2d
maxmind_proxy_fraud
hphosts_emd
hphosts_exp
hphosts_hjk
```

I understand that a custom list could be performed with update-ipsets and a local unfiltered DNS resolver, but official firehol_webclient support would be a great addition.

**Comment by ktsaou** [comment]
Thanks!

Sure, I'll add it.
But give me a few days to think of it and examine the lists you suggest in detail.
Probably I'll do it next weekend.

**Comment by abelbeck** [comment]
Fantastic !  Much appreciated.

**Comment by michaelkeuter** [comment]
That would be a great addition.

**Comment by abelbeck** [comment]
Bump, @ktsaou have you had time to formulate what blocklists would make a useful "firehol_webclient" IP list ?

I would expect "firehol_webclient" to be used in conjunction with "firehol_level1".

**Comment by ktsaou** [comment]
hm... You are right I forgot it completely.
This is a task for the weekend though. I'll try to do it this weekend.

**Comment by michaelkeuter** [comment]
Any update on this?

**Comment by ktsaou** [comment]
I think this is the configuration we need:

```
merge firehol_webclient ipv4 both \
	"malware" \
	"An IP blacklist made from blocklists that track IPs that a web client should never talk to." \
	"FireHOL" "http://iplists.firehol.org/" \
	feodo \
	palevo \
	ransomware_feed \
	ransomware_rw \
	sslbl_aggressive \
	zeus \
	cybercrime \
	atlas_phishing_30d \
	atlas_fastflux_30d \
	cleanmx_phishing \
	bambenek_c2 \
	blueliv_crimeserver_last_30d \
	dyndns_ponmocup \
	maxmind_proxy_fraud \
	hphosts_psh \
	hphosts_emd \
	hphosts_exp \
	hphosts_hjk \

```

What bothers me though, is:

1. several lists do not have a clear retention policy
2. hphosts will significantly affect hosting providers - i.e. multiple sites served by the same IP

Can you check it before adding it?

**Comment by abelbeck** [comment]
Related question to "hphosts", how do you do the DNS lookups ?  Do you use unbound or some such local native resolver to make sure you don't get "filtered" results like your would get from OpenDNS or an ISP ?

**Comment by abelbeck** [comment]
I don't have any experience with the "hphosts" lists, I see your point about shared-hosting sites yielding false positives.

Do you feel the "firehol_webclient" would be quite valuable without including the "hphosts" lists ?  Or possibly only including the hphosts_psh list ?

**Comment by ktsaou** [comment]
> Do you use unbound or some such local native resolver to make sure you don't get "filtered" results like your would get from OpenDNS or an ISP ?

On the netdata sites, where all these lists are updated, I run an autonomous DNS server. So, it is alone - it resolves everything by itself.

> I see your point about shared-hosting sites yielding false positives.

exactly. I have seen this happening in all lists I include them.

> Do you feel the "firehol_webclient" would be quite valuable without including the "hphosts" lists ? Or possibly only including the hphosts_psh list ?

hm... I cannot tell. We can try it and evaluate it hands on...

**Comment by abelbeck** [comment]
@ktsaou It seems the "blueliv_crimeserver_last_30d" from your list has issues.

I manually created a "firehol_webclient" by using your (above) list-of-lists without any "hphosts" lists and no "blueliv_crimeserver_last_30d".

The result is 42654 ipset entries, which is on the large size without adding more.

What do you think of this:
```
merge firehol_webclient ipv4 both \
    "malware" \
    "An IP blacklist made from blocklists that track IPs that a web client should never talk to." \
    "FireHOL" "http://iplists.firehol.org/" \
    feodo \
    palevo \
    ransomware_feed \
    ransomware_rw \
    sslbl_aggressive \
    zeus \
    cybercrime \
    atlas_phishing_30d \
    atlas_fastflux_30d \
    cleanmx_phishing \
    bambenek_c2 \
    dyndns_ponmocup \
    maxmind_proxy_fraud \
```
Additionally, while this list currently does not contain any hash:net entries, should the list file be named ```firehol_webclient.netset``` just in case to support future possible hash:net entries ?  Possibly your ```iprange``` might combine some of them as a hash:net as well.

**Comment by abelbeck** [comment]
Update, if we define "firehol_webclient" to be used in addition to "firehol_level1" we can simplify the list-of-lists to:
(Note: added "This list is to be used on top of firehol_level1")
```
merge firehol_webclient ipv4 both \
    "malware" \
    "An IP blacklist made from blocklists that track IPs that a web client should never talk to.  This list is to be used on top of firehol_level1." \
    "FireHOL" "http://iplists.firehol.org/" \
    ransomware_feed \
    sslbl_aggressive \
    zeus \
    cybercrime \
    atlas_phishing_30d \
    atlas_fastflux_30d \
    cleanmx_phishing \
    dyndns_ponmocup \
    maxmind_proxy_fraud \
```
The result is 30991 ipset entries.

**Comment by abelbeck** [comment]
@ktsaou I've been testing for the last few hours and the latest 9 entry list-of-lists above seems to work well in limited testing.  I have got a few unique OUTPUT/FORWARD hits by destination address, so far in all cases the IP's were in both "ransomware_feed" and "cleanmx_phishing".

**Comment by abelbeck** [comment]
Sigh, I just got http://bit.ly/ blocked by cleanmx_phishing :-(

**Comment by ktsaou** [comment]
yes, that is what I was talking about...

To avoid false positives, the list should include only the ones that are either:

1. too bad and should be excluded: abuse.ch lists are such
2. too recent (e.g 1-2 days max)

the result would be a very small IP lists and will provide very basic protection.

In general, client protection is too complex for layer 3 filtering. It has to happen at layer 7 (which again becomes almost impossible with SSL - except if you terminate SSL at a proxy and re-initiate it to the server).

**Comment by abelbeck** [comment]
Thanks @ktsaou for the insights, but if this stops one accidental phishing email click, this could be quite valuable.

Also, I see "cleanmx_phishing" has not been updated for 110 days.

So we are at this list-of-lists:
```
merge firehol_webclient ipv4 both \
    "malware" \
    "An IP blacklist made from blocklists that track IPs that a web client should never talk to.  This list is to be used on top of firehol_level1." \
    "FireHOL" "http://iplists.firehol.org/" \
    ransomware_feed \
    sslbl_aggressive \
    zeus \
    cybercrime \
    atlas_phishing_30d \
    atlas_fastflux_30d \
    dyndns_ponmocup \
    maxmind_proxy_fraud \
```
Should the "atlas_" be the _2d versions instead of the _30d ?

Indeed the "hphosts" do not belong here.

**Comment by ktsaou** [comment]
> Should the "atlas_" be the _2d versions instead of the _30d ?

The only difference is the possibility of false positives.

To my understanding, for a user, a perfectly valid link that does not work, will eventually lead to the removal of the blacklist, much like you did when you realized that bit.ly did not work. So, false positives in a user environment are totally unacceptable, especially if they are applied for 30 days. 

I would go with the 2d ones...

**Comment by abelbeck** [comment]
OK, I switched to _2d versions and use zeus_badips instead of zeus.

Here is the latest:
```
merge firehol_webclient ipv4 both \
    "malware" \
    "An IP blacklist made from blocklists that track IPs that a web client should never talk to.  This list is to be used on top of firehol_level1." \
    "FireHOL" "http://iplists.firehol.org/" \
    ransomware_feed \
    sslbl_aggressive \
    zeus_badips \
    cybercrime \
    atlas_phishing_2d \
    atlas_fastflux_2d \
    dyndns_ponmocup \
    maxmind_proxy_fraud \
```
Unique firehol_webclient ipsets: 10782

**Comment by ktsaou** [comment]
ok, can you test it a bit before releasing it?

**Comment by abelbeck** [comment]
> ok, can you test it a bit before releasing it?

Sure, I have a test firehol_webclient added on my edge router.  Also @michaelkeuter noticed zeus_badips is in firehol_level1, so that can be removed.

Here is the latest:
```
merge firehol_webclient ipv4 both \
    "malware" \
    "An IP blacklist made from blocklists that track IPs that a web client should never talk to.  This list is to be used on top of firehol_level1." \
    "FireHOL" "http://iplists.firehol.org/" \
    ransomware_feed \
    sslbl_aggressive \
    cybercrime \
    atlas_phishing_2d \
    atlas_fastflux_2d \
    dyndns_ponmocup \
    maxmind_proxy_fraud \
```
Unique firehol_webclient ipsets: 10653

Note that about 50% of the ipsets is from "cybercrime", not sure how false-positive-possible that is.

**Comment by abelbeck** [comment]
Quick Update,

The latest "firehol_webclient" is working well for me.

In fact, last evening the included "ransomware_feed" blocked an email malware link my wife accidentally clicked on.

I am seeing an occasional (one every day or two) false-positive from "ransomware_feed", in all cases they were labeled as "offline" in the "/feeds/csv/" data.  But, just as I was going to suggest you match for "online" in your parse_ransomwaretracker_feed() function in the ```update-ipsets``` script, the email malware link my wife clicked on was not yet in the "/feeds/csv/" data but did share the IP address of an "offline" entry.

In a false-positive case my wife had a bookmark to a cooking site what was on a shared-hosting site wrapping a wordpress site in an iframe.  She was happy to bookmark the wordpress site which was not blocked by "firehol_webclient".

For a home, small business, etc. I think the "firehol_webclient" gives a good balance of protection and false-positives.  Life still goes on if a valid shared-hosting site is not reachable for a few days. :-)

I would suggest "firehol_webclient" should give an occasional false-positive to be tuned properly.  IMO, this latest "firehol_webclient" is working well in that respect.

**Comment by michaelkeuter** [comment]
The latest version works fine for me too.

**Comment by abelbeck** [comment]
@ktsaou the only false-positives I have noticed are with the "ransomware_feed", and in all those cases the matching IP has a status of "offline" .  85% are "offline" in the "ransomware_feed".
```
$ grep -c '"online",' csv.txt 
1010
$ grep -c '"offline",' csv.txt 
5849
```
I'm not sure if the "ransomware_feed" should only include "online" entries, or possibly a new "ransomware_feed_online" list to be used by "firehol_webclient".

Regardless the latest "firehol_webclient" is working well for me.

**Comment by ktsaou** [comment]
Can you replace it with `ransomware_rw`?

Check this for more info: https://ransomwaretracker.abuse.ch/blocklist/

**Comment by abelbeck** [comment]
@ktsaou ransomware_rw is already in firehol_level1 so that would be redundant.

**Comment by ktsaou** [comment]
then we should remove `ransomware_feed`.

**Comment by abelbeck** [comment]
@ktsaou OK, do you think ransomeware_feed matching only "online" entries would add beyond ransomeware_rw ?

**Comment by ktsaou** [comment]
I think they should be the same. If they are online, the `_rw` list should include them.

**Comment by abelbeck** [comment]
@ktsaou I created a script to test, and surprisingly ```ransomeware_feed``` only containing "online" is almost unique to ```ransomware_rw```.

The total of ```ransomeware_feed``` only containing "online" is: 1309 (some duplicate IP's)

Of those IP's, 1289 are not in ```ransomware_rw``` and only 20 are in ```ransomware_rw```.

I would suggest in your parse_ransomwaretracker_feed() function in the update-ipsets script, only include "online" data:
```
parse_ransomwaretracker_feed() {
    $SED_CMD -n -e '/,"online",/p' | \
    $SED_CMD -e 's/^[[:space:]]*#.*//g' \
    ...
```

And then as proposed include ```ransomeware_feed``` in a new ```firehol_webclient``` list.

**Comment by abelbeck** [comment]
Possibly this is a better ```parse_ransomwaretracker_feed()``` approach for only "online" entries:
```
parse_ransomwaretracker_feed() {
  $SED_CMD -n -e 's/^"\(.*\)","\(.*\)","\(.*\)","\(.*\)","\(.*\)","\(online\)","\(.*\)","\(.*\)","\(.*\)","\(.*\)"$/\8/p' | \
  $SED_CMD -e '/^[[:space:]]*$/d' -e 's/|/\n/g'
}
```

**Comment by ktsaou** [comment]
merged it.

**Comment by ktsaou** [comment]
updates the site too.

**Comment by abelbeck** [comment]
@ktsaou Thank you very much !  Perfect.

Though ransomware_online started out fine, but now is 0 entries ???

**Comment by ktsaou** [comment]
hm... my bad! fixed it!

**Comment by abelbeck** [comment]
Great !  Thanks again.

**Comment by abelbeck** [comment]
@ktsaou There still seems to be an issue with ```ransomware_online```, it is using a stale source file, but ```ransomware_feed``` is getting updated.

The "last time updated by its maintainers" on the website is different between the two.

At this time of this writing there should be 1080 unique IP's for ```ransomware_online``` using this test script:
```
#!/bin/sh

parse_ransomwaretracker_online() {
  sed -r -n -e 's/^"(.*)","(.*)","(.*)","(.*)","(.*)","(online)","(.*)","(.*)","(.*)","(.*)"$/\8/p' | \
  sed -e 's/|/\n/g' | \
  sed -n -e '/^[0-9][0-9.]*$/p'
}

curl -sfL "https://ransomwaretracker.abuse.ch/feeds/csv/" | parse_ransomwaretracker_online | sort | uniq | wc -l
```

**Comment by ktsaou** [comment]
hm... this is what happens when I don't recall how to s/w I wrote works...

thanks for checking it...

I am fixing it...

**Comment by ktsaou** [comment]
and I think I fixed it.

**Comment by abelbeck** [comment]
@ktsaou Excellent, it now appears to be working as expected.
