### ISSUE TITLE
193.106.238.29

### ISSUE THREAD

**Issue by ksiadz666** [firehol/blocklist-ipsets#19]
Hi.
Could you please provide a reason for listing IP: 193.106.238.29?
Thanks in advance.

**Comment by ktsaou** [comment]
This is where it is listed:

```sh
# echo "193.106.238.29" | iprange - --compare-next *.{ip,net}set | grep -v ",0$"
stdin,firehol_webserver.netset,1,46549,1,50943602,50943602,1
stdin,ransomware_feed.ipset,1,2598,1,2598,2598,1
stdin,hphosts_emd.ipset,1,20772,1,20772,20772,1
```

- `firehol_webserver` (http://iplists.firehol.org/?ipset=firehol_webserver) is a composition of other lists (it includes `hphosts_emd`)
- `ransomware_feed` (http://iplists.firehol.org/?ipset=ransomware_feed) is managed by abuse.ch
- `hphosts_emd` (http://iplists.firehol.org/?ipset=hphosts_emd) lists hostnames, which aparantly includes one or more hostnames that resolve to this IP.

**Comment by ksiadz666** [comment]
Could you please PM me with list of offending hostnames or a link where it can be checked directly?

**Comment by ktsaou** [comment]
I am sorry but I don't know why these IP feeds list your IP.
I just know they list it.

You have to contact their maintainers for find out why. The links I gave you above have more information about the source feed I used and the maintainers' sites.

Keep in mind that for hphosts, you have to find the hostnames they list that resolve to your IP and contact them for information about these hostnames. If you ask them about IPs, they will not understand you.

**Comment by ksiadz666** [comment]
Great, thanks for your (quick) support :).
