### ISSUE TITLE
[firehol_webserver]: 23.247.128.0/17 (including 23.247.208.0/22) Listed Incorrectly

### ISSUE THREAD

**Issue by rcoulsell** [firehol/blocklist-ipsets#199]
The IP 23.247.208.0/22 was recently acquired through an ARIN Direct Allocation by FiberFly, LLC.
This can be verified via: https://search.arin.net/rdap/?query=23.247.208.0%2F22
FiberFly is a rural internet service provider (ISP), serving parts of Waxahachie, TX in the USA.
This can be verified at: https://fiberfly.com

We do not perform hosting services. We only provide home and business internet connections to our rural community.
Apparently the previous holder of this IP block, (M247 Ltd) was a hosting company, hence this block being included in your list.

Please update to remove this block from your list 'firehol_webserver'.

Row 38: Remove '23.247.128.0/17'

This /17 block was been split among numerous organizations through ARIN via Direct Allocation on around Oct 2021:
23.247.128.0/22 - IDC SPACE INC
23.247.132.0/22 - BRAIN PEACE SCIENCE FOUNDATION, INC
23.247.136.0/22 - Black Mesa Corporation
23.247.140.0/22 - Sky Fi
23.247.144.0/22 - VPB INC.
23.247.148.0/22 - City of Marshall
23.247.152.0/22 - VPSie INC
23.247.156.0/22<-- Not Assigned by ARIN
23.247.160.0/22 - One
23.247.164.0/22 - I.D. Logique
23.247.168.0/22 - Nasulex Networks
23.247.172.0/22 - Optelli Fiber LLC
23.247.176.0/22 - SDWANET LLC
23.247.180.0/24 - Ridge Wireless LLC
23.247.184.0/23 - PeopleHedge Corp
23.247.188.0/23 - Raptor Engineering, LLC
23.247.192.0/22 - I.S.F Quebec, Inc
23.247.196.0/22 - Clearwave Broadband Networks Inc.
23.247.200.0/22 - GHOST CLOUD LLC
23.247.204.0/22 - Estherville Communications LLC
23.247.208.0/22 - fiberfly <<<--------------------------------------------------------This is us!!!
23.247.212.0/22 - nextdns, Inc.
23.247.216.0/22 - City of Sylvester
23.247.220.0/22 - Data Stream
23.247.224.0/22 - BluBroadband ISP
23.247.228.0/22 - Kingsburg Media Foundation
23.247.232.0/22 - Voxtelesys LLC
23.247.236.0/22 - campuscolo.com
23.247.240.0/22 - Fortlab
23.247.244.0/22 - David & Denis Inc.
23.247.248.0/24 - RCG Communications, LLC
23.247.249.0/24 - Jackson County Memorial Hospital
23.247.250.0/23 - G5 INTERNET, LLC
23.247.252.0/24 - Computer Marketing Corporation
23.247.253.0/24 - Madon Damien, Sole Proprietorship
23.247.254.0/23 - HARRIS COUNTY TOLL ROAD AUTHORITY

**Comment by rcoulsell** [comment]
23.247.128.0/17 should also be removed from the firehol_pushing_inertia_blocklist. See line 95.

**Comment by rcoulsell** [comment]
@vlvkobal , @simonnagl , @philwhineray , @ktsaou , @ilyam8 , @fawaf , @alonbl 
See above issue above inadvertently impacting multiple organizations. Since commits to these groups have only happened twice in the past 5-6 months... tagging you all to see if you can help make the minor changes to the two lists.

Namely this is manifesting in bigdatacloud.com miss-characterizing the risk of traffic originating from these IP Blocks. And customers on these blocks being unable to use common consumer web services.

Thank you for your help.

**Comment by fawaf** [comment]
i have read-only access unfortunately, so i can't help you there, otherwise i would try to. :)

**Comment by rcoulsell** [comment]
Thanks @fawaf !

@vlvkobal , @simonnagl , @philwhineray , @ktsaou , @ilyam8 , @alonbl
Are any of you able to make the change?

**Comment by ilyam8** [comment]
Hi, @rcoulsell. I can't help either, unfortunately. I see this repo is updated automatically once a day (and the history is [pruned with each update](https://github.com/firehol/blocklist-ipsets/issues/51#issuecomment-353001354)). It is a compilation of reputation lists provided by 3rd-party services. Perhaps you need to contact the service and ask them to remove the range (that is [how to find out what service has listed it](https://github.com/firehol/blocklist-ipsets/issues/13#issuecomment-242962164)).

^^ That is my opinion based only on open/closed issues/PRs.

I guess @ktsaou is the only person who can help you here

**Comment by philwhineray** [comment]
That's right; the firehol lists are just an aggregate of other publically available lists. We don't (and realistically can't) actively manage these sources.  To give an idea of the scale, IIRC the history gets pruned because the size of data / rate of churn was more than github was willing to accept and this is the compromise.

You really need to identify the source lists that your IPs have been added  to and deal with their admins. Once they are removed from those they will be removed from the firehol lists automatically and you will also have unblocked them for anyone using those lists directly.

The source lists for each firehol list is included on the site http://iplists.firehol.org/

Hope that helps

**Comment by rcoulsell** [comment]
Just ran a command in powershell on the entire repo I just cloned down (`Get-ChildItem -Recurse | Select-String "23.247.128.0/17" -List | Select Path`) It came back with only the two entries I previously listed above:

\blocklist-ipsets-master\firehol_webserver.netset <-- includes: maxmind_proxy_fraud, myip, pushing_inertia_blocklist, stopforumspam_toxic,
\blocklist-ipsets-master\pushing_inertia_blocklist.netset <-- This is he one that is creating the issue and feeding the webserver listing.

Creating a ticket on @pushinginertia 's ip-blacklist.conf file for an update to remove this block:
https://github.com/pushinginertia/ip-blacklist/issues/11

**Comment by rcoulsell** [comment]
Dan (@pushinginertia) was able to update the underlying feed.

Closing this ticket.

Thank you all for pointing me in the right direction.
