### ISSUE TITLE
[tor_exits]: not updating

### ISSUE THREAD

**Issue by chris-kennedy** [firehol/blocklist-ipsets#219]
The site indicates that it hasn't updated since September 30th, 2021. I am able to download the source file without issue and it has data from today.

**Comment by Belgarion** [comment]
According to https://iplists.firehol.org/?ipset=tor_exits the fetch errors started just around the time when let's encrypt old root certificate expired https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

So whatever server they run the updates from needs updated ca-certificates.

**Comment by chris-kennedy** [comment]
Not sure when, but this issue has been resolved.
