### ISSUE TITLE
127.0.0.1 and 8.8.8.8?

### ISSUE THREAD

**Issue by Ins1ghtLabs** [firehol/blocklist-ipsets#23]
8.8.8.8 found in
["cleantalk_updated_30d", "packetmail_emerging_ips", "hphosts_psh", "cleantalk_30d", "firehol_abusers_30d", "hphosts_fsa", "firehol_webserver", "cleantalk_updated_7d", "cleantalk_7d"]

127.0.0.1 found in 
["nullsecure", "botscout_30d", "botscout_7d", "hphosts_ats", "hphosts_exp", "hphosts_mmt", "hphosts_psh", "jigsaw_malware", "hphosts_hjk", "threatcrowd", "hphosts_fsa", "ransomware_feed", "hphosts_hfs", "firehol_webserver", "hphosts_grm", "hphosts_pha", "hphosts_emd", "hphosts_wrz"]

seriously?

**Comment by ktsaou** [comment]
well, this what these lists do.
I don't filter anything...

keep in mind that many lists are to be used for either inbound or outbound filtering. Others are to be used exclusively on the internet facing interface.

For example filtering packets with source IP 127.0.0.0/8 (and all other private IPs) on the internet facing interface is a good practice. You should do this, independently of what the lists match.

On the other 8.8.8.8 is the google DNS server. I think it should be justified for this DNS server to have participated in DNS amplification attacks, thus be included in IP lists (although the maintainers should have whitelisted this).

**Comment by Ins1ghtLabs** [comment]
Got it, thanks.
