### ISSUE TITLE
SPAMHAUS_DROP not current

### ISSUE THREAD

**Issue by steveg2088** [firehol/blocklist-ipsets#248]
Hi, I am not sure if you noticed.  Usually spamhaus_drop is updated regularly but firehol's version is > 2 weeks old.  
Meanwhile, if you look at the source list on the spamhaus website, it is current.  

Edit: Add dshield to the list as it also has not been maintained in > 2 weeks

Perhaps an issue with the firehol load sh ?

**Comment by StretchLegs** [comment]
I've noticed the same. I'm using these lists from the maintainers site until this issue is fixed.

**Comment by steveg2088** [comment]
looks like it has been fixed
