### ISSUE TITLE
Additional DataPlane.org SIP-based feeds

### ISSUE THREAD

**Issue by jtkdpu** [firehol/blocklist-ipsets#25]
Two small new feeds that you may wish to incorporate into the project:

  * [SIP Invitation](https://dataplane.org/sipinvitation.txt)
  * [SIP Registration](https://dataplane.org/sipregistration.txt)

Original DataPlane.org family request: #16

**Comment by ktsaou** [comment]
nice! adding them now...

**Comment by ktsaou** [comment]
Added the code: https://github.com/firehol/firehol/commit/2c80e74ce191be0324dfcce16e915c04f0bea685

**Comment by ktsaou** [comment]
Here they are:

- http://iplists.firehol.org/?ipset=dataplane_sipinvitation
- http://iplists.firehol.org/?ipset=dataplane_sipregistration

Thank you!
