### ISSUE TITLE
Secret attackers???

### ISSUE THREAD

**Issue by szepeviktor** [firehol/blocklist-ipsets#3]
Good morning!

I think my websites are the premier attack targets of the Internet because the attacking IP-s are not on any blacklist.

```bash
$ wc -l ../szerver4
803 ../szerver4
$ ls *.ipset | xargs -I %% grep -Fx -f %% ../szerver4 | sort | uniq | wc -l
370
$ ls *.netset | xargs -I %% grepcidr -f %% ../szerver4 | sort | uniq | wc -l
376
```

**Comment by szepeviktor** [comment]
@ktsaou Could you please help to explain this?

**Comment by ktsaou** [comment]
What is `szerver4`?

Generally you cannot grep these files. This is why I developed `iprange`.
Check this example:

file A:
```txt
1.2.3.4
```

file B:
```txt
1.2.0.0/16
```

You cannot grep them. They do not match.

You should install the development version of FireHOL from github. When you install it, a command line called `iprange` is installed.

Then to find the common IPs in 2 sets you will need to run:

```sh
iprange --common fileA fileB
```

This will print the common IPs/subnets to both files.

run `iprange -h` for full usage.

**Comment by szepeviktor** [comment]
Thank you for your answer.

I've used `grep` to search in ipsets, and [`grepcidr`](https://packages.debian.org/jessie/grepcidr) to search in netsets. Now I've realised the `grepcidr` is faster even for single addresses.

`szerver4` is the file with the fail2ban-ned IP-s of the previous days.

My aim to reduce fail2ban notification emails during botnet attacks.

You can see in the first comment that I have non-zero results.
Could you help me what to do? Would it help if I send you the IP list?

**Comment by ktsaou** [comment]
Sorry, I didn't really read the second line.

Yes please do so. Give me a link to download them.

**Comment by ktsaou** [comment]
or you can just paste them here... they are just 803 IPs
I will tell you which sets its matches among all them...

**Comment by szepeviktor** [comment]
OK. Here they are.

```
1.186.154.103
2.50.153.126
2.90.14.177
2.218.134.248
2.225.225.130
5.9.36.66
5.12.190.99
5.13.180.110
5.13.218.201
5.14.76.25
5.15.78.103
5.36.174.216
5.45.72.83
5.54.133.109
5.66.23.120
5.69.67.76
5.79.68.161
5.102.232.51
5.144.96.23
5.196.72.199
5.196.228.99
5.199.130.188
5.226.102.211
5.246.181.178
5.246.188.9
12.26.161.5
14.175.118.2
18.238.2.85
23.116.121.143
23.125.241.121
24.246.35.172
27.34.5.103
27.89.122.91
27.123.171.199
31.16.74.240
31.25.240.93
31.50.91.138
31.59.80.64
31.154.92.224
31.185.225.202
31.192.35.17
36.80.96.78
36.80.96.88
36.231.185.128
37.104.215.140
37.106.224.166
37.107.0.254
37.115.188.178
37.145.154.210
37.157.208.30
37.201.231.92
37.201.240.90
37.202.85.33
37.211.121.105
37.220.117.52
37.221.243.242
39.32.108.245
39.32.211.110
39.36.223.7
39.42.208.54
39.43.20.247
39.49.84.231
39.54.24.42
39.71.251.11
39.120.213.170
41.34.226.133
41.66.194.175
41.72.121.178
41.78.76.142
41.96.86.215
41.102.130.98
41.102.242.97
41.105.49.168
41.110.9.11
41.207.17.121
41.207.201.220
41.207.252.142
41.208.215.148
41.225.198.94
41.236.234.254
41.248.34.39
41.254.9.106
42.113.205.60
42.114.9.29
42.115.81.190
42.201.234.206
43.243.213.61
43.247.159.38
45.64.225.43
45.73.53.192
45.112.58.130
45.114.60.21
45.115.190.191
46.39.231.78
46.49.41.198
46.55.15.228
46.97.200.70
46.109.218.223
46.116.116.64
46.117.142.18
46.150.37.131
46.166.136.114
46.166.170.3
46.182.106.190
46.193.143.250
46.195.151.168
46.197.57.26
46.233.0.70
46.236.154.82
47.63.216.168
49.144.230.112
49.145.213.12
49.146.226.114
49.149.136.11
49.150.28.106
49.150.68.6
49.150.231.123
49.205.180.170
49.244.72.50
50.19.1.73
50.65.56.53
51.174.67.78
51.254.130.60
52.23.228.230
54.69.167.100
54.69.167.182
54.165.251.13
54.183.254.90
54.193.18.89
58.97.190.165
58.143.60.84
58.233.175.229
59.101.3.43
59.189.224.92
60.230.125.81
60.240.9.26
62.1.49.23
62.10.187.245
62.45.135.109
62.102.148.67
62.141.45.246
62.196.140.15
62.210.107.201
62.210.148.233
62.219.163.146
62.234.2.110
62.252.7.24
65.29.107.48
65.95.64.211
65.183.4.146
65.183.154.104
66.69.10.250
68.108.74.246
68.114.238.106
68.123.204.28
68.142.232.21
69.12.92.26
69.22.174.108
69.30.215.142
69.163.144.121
69.197.169.202
69.247.214.184
70.49.200.200
70.74.14.75
71.81.75.121
71.87.108.171
71.95.3.172
71.180.50.22
72.22.128.224
72.27.72.245
72.27.83.3
72.178.70.76
73.4.49.248
73.202.91.247
74.57.159.56
74.208.16.114
74.208.16.123
74.208.75.106
75.90.135.76
75.90.137.240
75.133.195.60
76.30.141.123
76.103.134.253
77.38.32.182
77.38.104.68
77.40.46.253
77.46.174.10
77.46.194.108
77.49.138.222
77.49.156.50
77.81.227.24
77.94.204.58
77.109.139.87
77.125.136.179
77.125.146.241
77.144.124.111
77.147.3.207
77.222.1.9
77.236.206.226
77.247.181.163
78.0.235.24
78.12.29.215
78.19.42.53
78.21.107.220
78.49.252.119
78.58.199.25
78.61.241.53
78.62.99.180
78.62.110.237
78.96.162.169
78.208.90.163
79.33.220.30
79.41.102.203
79.53.75.120
79.101.139.136
79.103.179.172
79.112.83.155
79.113.0.51
79.114.10.243
79.116.211.195
79.117.64.230
79.119.106.69
79.119.243.57
79.120.10.98
79.126.195.7
79.143.111.253
79.146.61.185
79.166.95.183
79.176.51.241
79.177.175.218
79.180.133.171
79.180.202.158
79.182.201.233
80.119.204.173
80.174.18.69
80.183.73.88
80.223.15.2
80.227.8.166
80.234.47.148
81.21.67.235
81.89.96.89
81.108.35.140
81.158.142.167
81.167.140.22
81.183.11.162
81.215.199.54
82.8.186.109
82.10.214.77
82.12.6.32
82.31.47.58
82.53.47.62
82.98.160.77
82.168.99.148
82.192.45.246
82.194.152.114
82.213.48.202
82.214.116.96
82.241.128.241
82.242.64.30
83.28.111.112
83.54.203.115
83.110.4.107
83.110.222.197
83.137.253.9
83.137.253.120
83.217.212.185
83.246.139.62
84.16.221.34
84.85.161.236
84.109.127.242
84.126.101.244
84.211.20.4
84.240.27.61
85.25.103.119
85.50.204.39
85.64.157.77
85.96.1.144
85.120.146.65
85.120.174.38
85.130.137.99
85.135.47.182
85.137.148.235
85.179.204.5
85.207.128.17
85.214.247.93
85.254.75.104
85.254.75.148
85.254.75.184
86.0.27.252
86.10.36.100
86.16.31.34
86.84.250.127
86.86.209.209
86.98.6.191
86.98.149.193
86.104.194.137
86.122.108.118
86.122.110.235
86.123.238.117
86.144.225.75
86.169.71.183
86.204.20.219
87.20.56.174
87.68.82.125
87.69.224.237
87.101.207.150
87.106.149.183
87.126.41.35
87.229.87.255
87.237.139.51
87.241.113.44
87.248.0.87
88.9.96.21
88.22.94.3
88.119.150.171
88.178.240.37
88.183.45.63
88.198.23.35
88.231.182.30
88.236.196.83
88.249.176.241
89.46.250.97
89.133.141.193
89.138.194.0
89.147.251.159
89.169.198.183
89.180.144.110
89.180.153.184
89.205.106.94
89.210.67.45
89.219.186.153
89.223.47.213
89.230.32.36
89.233.254.65
89.236.214.130
89.238.188.119
89.250.2.244
90.77.135.99
90.176.180.191
90.191.18.13
90.195.44.21
90.195.76.39
90.198.51.38
90.230.145.160
91.90.15.152
91.105.69.17
91.181.15.253
91.192.2.206
91.200.13.64
91.206.210.183
91.213.8.84
91.218.15.194
91.238.59.71
92.8.60.125
92.53.59.126
92.55.87.195
92.74.175.159
92.80.139.69
92.84.153.143
92.86.31.58
92.99.45.224
92.99.115.208
92.124.108.43
92.143.37.10
92.209.180.175
92.222.69.188
92.237.0.181
92.244.146.89
93.12.77.51
93.24.30.45
93.33.131.228
93.45.64.148
93.55.190.79
93.66.227.235
93.70.251.5
93.77.137.200
93.103.38.80
93.108.45.12
93.113.157.7
93.115.95.205
93.115.95.207
93.130.68.44
93.143.21.99
93.168.83.178
93.172.10.149
93.172.183.17
93.174.90.30
93.180.68.68
93.184.93.156
94.0.150.39
94.13.99.155
94.43.197.8
94.45.195.215
94.68.180.116
94.99.37.28
94.177.42.196
94.189.233.141
94.189.250.190
94.190.4.203
94.197.120.66
94.200.29.94
94.203.77.209
94.231.167.229
94.242.246.24
94.249.61.224
95.42.249.25
95.56.93.127
95.56.173.78
95.90.227.121
95.93.106.98
95.93.174.11
95.95.181.190
95.103.129.111
95.130.9.140
95.148.60.246
95.158.186.172
95.165.129.128
95.180.41.120
95.185.19.228
95.186.212.100
95.188.131.206
95.211.149.204
95.211.229.158
95.220.26.210
96.47.226.20
96.245.196.120
97.89.4.156
98.30.178.68
99.124.197.204
101.50.74.174
101.63.207.126
101.127.167.18
101.186.45.91
101.235.14.85
103.17.74.70
103.22.173.110
103.231.5.66
103.246.64.36
103.248.248.219
103.249.181.120
103.251.176.6
104.35.202.55
104.137.135.115
104.208.33.212
104.232.3.33
104.235.222.209
105.101.110.148
105.102.96.29
105.102.190.151
105.103.23.175
105.107.90.194
105.156.230.113
105.156.232.249
105.184.157.212
105.224.226.29
105.226.132.26
105.226.173.95
105.236.104.54
107.181.174.84
108.17.6.48
108.29.67.207
109.57.120.194
109.61.231.212
109.64.194.22
109.64.209.192
109.65.34.235
109.92.57.115
109.93.168.83
109.96.36.215
109.121.98.8
109.122.124.199
109.123.218.175
109.162.237.194
109.166.140.192
109.175.205.131
109.185.116.39
109.205.17.16
109.252.77.21
110.20.206.1
110.78.152.4
110.93.217.10
110.168.29.188
110.195.180.100
110.195.181.12
111.88.32.127
111.88.229.61
111.93.148.98
111.118.185.97
111.119.39.183
111.235.89.219
112.87.217.228
112.196.171.169
112.198.118.18
112.198.118.139
112.198.118.222
112.204.223.135
112.205.69.17
112.209.98.168
112.210.246.223
112.211.179.93
112.211.188.49
113.11.250.211
113.23.66.106
113.66.41.11
113.161.81.14
113.199.162.138
115.21.27.185
115.134.174.136
116.74.8.133
116.88.121.20
117.3.116.65
117.196.233.97
117.201.236.111
117.214.248.118
117.241.214.68
119.26.64.118
119.73.101.16
119.104.9.54
119.104.15.73
119.154.207.117
119.193.34.42
119.235.49.195
119.235.54.172
120.59.41.42
120.155.58.6
121.54.32.109
121.54.32.135
121.54.32.142
121.54.32.168
121.54.44.92
121.54.44.95
121.54.58.243
121.115.108.152
121.141.35.17
121.156.198.183
121.170.94.11
122.2.17.85
122.52.153.90
122.61.113.243
122.108.230.127
122.151.93.34
122.201.31.227
123.201.197.229
123.201.208.45
123.237.167.114
123.254.192.44
124.29.242.197
125.138.124.23
126.64.139.34
129.123.7.7
130.105.104.240
130.185.155.146
130.193.178.96
130.193.189.192
130.255.154.184
131.170.5.1
134.226.214.248
138.219.135.178
139.190.35.255
140.237.29.245
141.239.152.53
142.4.214.124
142.54.184.178
149.88.118.10
149.129.136.8
149.202.47.181
149.202.98.160
151.1.158.94
151.80.44.159
151.228.166.40
152.236.78.194
152.237.95.134
152.238.108.57
154.66.24.46
154.70.216.129
154.120.87.140
158.69.200.185
162.247.72.202
162.247.72.217
171.25.193.78
173.165.161.165
173.168.173.7
173.171.183.246
173.254.216.69
174.52.250.186
174.95.166.127
175.136.39.144
175.142.135.112
175.142.188.70
175.156.86.83
175.159.98.97
175.201.167.191
175.209.167.79
176.9.25.72
176.9.39.218
176.10.99.202
176.16.84.156
176.27.194.185
176.31.191.26
176.92.195.11
176.123.87.131
176.126.252.11
176.203.145.112
177.4.49.95
177.33.177.1
177.42.106.150
177.65.102.187
177.133.33.154
177.133.156.205
177.180.100.147
177.180.215.14
177.194.168.235
178.88.220.230
178.124.170.150
178.128.20.135
178.128.69.206
178.132.216.6
178.143.191.154
178.149.248.163
178.153.18.226
178.167.254.127
178.175.122.85
178.175.252.66
178.211.179.252
178.221.177.14
178.222.195.112
178.223.8.138
178.223.122.222
179.108.142.193
179.110.34.203
179.210.63.215
179.216.47.188
180.190.78.2
180.190.90.51
180.191.139.240
180.191.155.173
180.193.115.224
180.211.248.148
180.211.253.92
180.232.85.198
180.234.144.222
181.1.99.59
181.55.174.218
181.164.243.201
182.69.86.110
182.73.66.66
182.160.35.49
182.160.39.95
182.160.39.136
182.178.225.97
182.180.164.110
182.185.2.244
182.185.131.66
182.187.69.199
182.190.248.58
182.216.200.206
182.222.132.63
182.239.210.145
183.87.152.118
183.206.166.17
183.238.82.183
184.3.250.125
184.59.0.140
184.145.242.78
185.5.153.36
185.34.16.17
185.34.33.2
185.53.244.250
185.54.162.130
185.88.25.42
185.88.25.146
185.92.73.125
185.104.120.4
186.9.75.193
186.45.235.157
186.67.158.43
187.95.117.24
187.195.110.53
188.2.91.14
188.17.122.220
188.24.18.153
188.26.219.178
188.50.159.102
188.69.193.174
188.93.239.14
188.116.224.178
188.126.143.213
188.135.214.244
188.142.214.168
188.143.124.72
188.143.234.90
188.214.153.15
188.247.92.78
189.5.30.102
189.19.144.49
189.24.47.210
189.27.133.212
189.51.137.41
189.63.152.144
189.68.191.198
189.103.208.130
189.114.233.127
189.217.97.61
190.16.213.55
190.52.134.154
190.92.44.117
190.92.44.152
190.139.235.17
190.163.202.179
191.7.28.18
191.23.118.57
191.183.95.27
191.248.123.44
192.116.142.154
192.187.126.163
193.53.83.25
193.77.56.233
193.140.109.2
193.201.227.21
193.232.52.247
194.150.168.79
194.150.168.95
195.3.144.88
195.34.244.195
195.99.36.97
195.240.131.226
195.254.235.75
196.206.145.11
196.217.157.101
196.248.108.208
197.0.76.193
197.15.12.35
197.15.213.68
197.88.138.26
197.115.69.231
197.163.85.218
197.206.93.114
197.210.227.87
197.213.206.87
197.225.228.179
198.8.80.75
198.27.69.113
198.50.145.72
198.57.197.95
199.187.122.91
199.192.224.196
199.212.27.187
200.1.211.123
200.24.16.166
200.104.200.185
200.192.211.210
200.195.158.27
201.8.2.11
201.37.160.81
201.51.52.34
201.51.163.30
201.80.190.132
201.95.26.8
201.130.152.172
201.161.151.249
202.21.181.117
202.69.60.227
202.134.13.131
202.142.90.62
202.156.15.42
202.166.31.27
203.106.213.185
203.147.90.215
204.45.18.50
204.195.52.139
204.232.238.204
207.81.148.73
207.204.125.72
208.113.238.164
209.159.138.19
210.56.85.1
210.186.123.21
211.189.241.52
212.97.132.130
212.117.180.21
212.121.104.124
212.158.152.2
212.200.82.96
212.251.163.105
213.14.94.18
213.57.108.77
213.112.77.111
213.156.110.111
213.164.115.226
213.198.238.113
213.252.244.244
216.104.202.50
216.218.134.12
216.245.199.234
217.43.107.85
217.77.223.186
217.165.113.131
218.102.215.115
219.94.128.197
219.250.2.130
220.124.96.176
220.240.129.51
222.154.166.198
```

**Comment by szepeviktor** [comment]
I was not able to go above 48%.

**Comment by ktsaou** [comment]
ok, here they are:

szervers4:
totals: 803 lines read, 803 distinct IP ranges found, 1 CIDR prefixes, 803 CIDRs printed, 803 unique IPs

Here are what it matches by executing:

```sh
iprange --header --compare-first /tmp/szerver4 *.{ip,net}set |\
   grep -v ",0$" |\
   sort -u |\
   tr "," "|"
```

name|entries|unique_ips|common_ips
---|---|---|---|
alienvault_reputation.ipset|196728|196728|8
bi_any_2_1d.ipset|842|842|4
bi_any_2_30d.ipset|6454|6454|15
bi_any_2_7d.ipset|2597|2597|13
bi_ftp_2_30d.ipset|265|265|1
bi_http_2_30d.ipset|86|86|6
bi_ssh_2_30d.ipset|4942|4942|9
bitcoin_nodes_30d.ipset|47382|47382|1
blocklist_de_apache.ipset|19566|19566|239
blocklist_de_bots.ipset|2604|2604|3
blocklist_de_bruteforce.ipset|8247|8247|238
blocklist_de.ipset|29025|29025|244
blocklist_de_mail.ipset|15446|15446|1
blocklist_de_ssh.ipset|1852|1852|1
blocklist_de_strongips.ipset|141|141|1
blocklist_net_ua.ipset|17622|17622|28
bm_tor.ipset|6420|6420|48
botscout_1d.ipset|1278|1278|34
botscout_30d.ipset|21558|21558|54
botscout_7d.ipset|6318|6318|51
botscout.ipset|51|51|1
cruzit_web_attacks.ipset|4739|4739|3
cybercrime.ipset|5353|5353|12
darklist_de.netset|738|130392|1
dm_tor.ipset|6406|6406|48
dragon_http.netset|950|294144|3
dronebl_anonymizers.netset|167241|174137|8
dronebl_worms_bots.netset|23639|25308|4
dshield_30d.netset|4181|1096704|7
dshield_7d.netset|1514|394240|1
et_tor.ipset|6290|6290|49
firehol_anonymous.netset|27094|85454|50
firehol_level2.netset|28902|137708|309
firehol_level3.netset|100526|10992123|70
firehol_proxies.netset|20739|23787|33
gofferje_sip.netset|507|1094315|5
greensnow.ipset|11834|11834|105
iblocklist_ads.netset|3314|888645|4
iblocklist_bogons.netset|2699|666661539|23
iblocklist_cruzit_web_attacks.netset|4711|4733|3
iblocklist_edu.netset|40792|227983904|9
iblocklist_hijacked.netset|535|9177856|1
iblocklist_isp_att.netset|35|55845128|2
iblocklist_isp_charter.netset|21|6138112|6
iblocklist_isp_comcast.netset|33|45121536|6
iblocklist_isp_twc.netset|56|15015936|3
iblocklist_isp_verizon.netset|22|18087936|4
iblocklist_level1.netset|218306|764928098|16
iblocklist_level2.netset|72950|348710251|10
iblocklist_level3.netset|17812|139104927|34
iblocklist_onion_router.netset|6174|6238|48
iblocklist_org_blizzard.netset|7|16794627|1
iblocklist_pedophiles.netset|22798|872217|6
iblocklist_rangetest.netset|515|4346058|8
iblocklist_spider.netset|734|860168|1
iblocklist_spyware.netset|3297|339021|1
iw_spamlist.ipset|3601|3601|1
lashback_ubl.ipset|371205|371205|12
maxmind_proxy_fraud.ipset|446|446|32
myip.ipset|2672|2672|2
nixspam.ipset|22953|22953|1
openbl_180d.ipset|14242|14242|4
openbl_30d.ipset|2480|2480|2
openbl_360d.ipset|28764|28764|7
openbl_60d.ipset|4830|4830|3
openbl_7d.ipset|780|780|2
openbl_90d.ipset|7458|7458|3
openbl_all.ipset|107331|107331|8
php_commenters_1d.ipset|91|91|3
php_commenters_30d.ipset|807|807|18
php_commenters_7d.ipset|281|281|7
php_commenters.ipset|50|50|2
php_dictionary_30d.ipset|1240|1240|1
php_harvesters_1d.ipset|77|77|4
php_harvesters_30d.ipset|631|631|4
php_harvesters_7d.ipset|199|199|4
php_harvesters.ipset|50|50|4
php_spammers_30d.ipset|1208|1208|1
proxylists_1d.ipset|6691|6691|1
proxylists_30d.ipset|17360|17360|1
proxylists_7d.ipset|9915|9915|1
proxylists.ipset|4730|4730|1
proxyrss_1d.ipset|6421|6421|1
proxyrss_30d.ipset|16888|16888|1
proxyrss_7d.ipset|9557|9557|1
proxyrss.ipset|4505|4505|1
proxyspy_1d.ipset|1213|1213|1
proxyspy_30d.ipset|6382|6382|1
proxyspy_7d.ipset|2825|2825|1
pushing_inertia_blocklist.netset|734|37908616|43
ri_web_proxies_30d.ipset|4258|4258|1
ri_web_proxies_7d.ipset|1316|1316|1
sblam.ipset|11730|11730|46
snort_ipfilter.ipset|9508|9508|44
sorbs_dul.netset|533752|351501549|132
sorbs_new_spam.netset|12382|12516|1
sorbs_noserver.netset|11894|21181534|22
sorbs_recent_spam.netset|41401|42458|1
sorbs_web.netset|5284892|5660056|14
sslbl_aggressive.ipset|1044|1044|1
stopforumspam_180d.ipset|415441|415441|67
stopforumspam_1d.ipset|5279|5279|45
stopforumspam_30d.ipset|78928|78928|58
stopforumspam_365d.ipset|912590|912590|70
stopforumspam_7d.ipset|24311|24311|56
stopforumspam_90d.ipset|220782|220782|63
stopforumspam.ipset|220823|220823|64
stopforumspam_toxic.netset|79|551511|1
talosintel_ipfilter.ipset|9524|9524|44
tor_exits_1d.ipset|1067|1067|49
tor_exits_30d.ipset|3018|3018|50
tor_exits_7d.ipset|1482|1482|49
tor_exits.ipset|973|973|48

These are the countries they match:

name|entries|unique_ips|common_ips
---|---|---|---|
anonymous.netset|143|55381|3
continent_af.netset|1760|82187639|46
continent_as.netset|15981|871795336|255
continent_eu.netset|31370|753642059|333
continent_na.netset|16719|1733361597|106
continent_oc.netset|6498|57408602|15
continent_sa.netset|2750|146404832|51
country_ae.netset|179|3783522|11
country_af.netset|78|172963|1
country_al.netset|112|383252|2
country_am.netset|107|616880|1
country_ar.netset|1018|19018000|4
country_at.netset|1355|11811784|1
country_au.netset|5622|49652472|12
country_az.netset|127|753680|2
country_bb.netset|52|189073|1
country_bd.netset|410|1106184|5
country_be.netset|1241|28868912|2
country_bg.netset|602|4625364|4
country_bh.netset|71|476156|1
country_br.netset|1576|82387918|39
country_by.netset|119|1902617|1
country_ca.netset|6767|80309147|15
country_ch.netset|2030|21035918|2
country_ci.netset|30|198272|2
country_cl.netset|655|10255633|4
country_cn.netset|4089|335945582|8
country_co.netset|498|17433808|2
country_cy.netset|236|1091790|2
country_cz.netset|1144|9194655|7
country_de.netset|7462|122534581|21
country_dk.netset|1030|13250121|2
country_dz.netset|61|3788345|12
country_ee.netset|245|1405273|1
country_eg.netset|183|17346708|3
country_es.netset|1962|30743158|10
country_fi.netset|875|13740673|1
country_fj.netset|33|146736|1
country_fr.netset|6899|84855601|26
country_gb.netset|9657|127030038|36
country_ge.netset|163|1201743|3
country_gh.netset|108|826013|2
country_gr.netset|408|6309290|11
country_hk.netset|1952|11961186|3
country_hn.netset|231|518114|2
country_hr.netset|255|2415262|2
country_hu.netset|454|5927383|5
country_id.netset|1304|19099320|3
country_ie.netset|1025|8378688|3
country_il.netset|505|7885896|26
country_in.netset|2902|38137351|32
country_iq.netset|143|679476|5
country_ir.netset|864|11650123|4
country_it.netset|2748|53977942|20
country_je.netset|45|68596|2
country_jm.netset|85|274702|4
country_jo.netset|129|680340|4
country_jp.netset|2847|204400580|7
country_kr.netset|940|112426449|18
country_kz.netset|255|2968588|3
country_lt.netset|330|2608455|10
country_lu.netset|245|1434431|2
country_lv.netset|374|1859829|6
country_ly.netset|37|335364|1
country_ma.netset|52|6744960|5
country_md.netset|350|1360520|3
country_me.netset|41|221456|3
country_mk.netset|88|687632|5
country_mn.netset|68|214656|4
country_mu.netset|262|2051837|1
country_mv.netset|15|58368|1
country_mx.netset|662|28905817|4
country_my.netset|526|6688718|7
country_ng.netset|427|2728090|3
country_nl.netset|5111|50562294|19
country_no.netset|1058|16146767|6
country_np.netset|83|503425|4
country_nz.netset|836|7144953|2
country_om.netset|44|905236|1
country_ph.netset|519|5506676|33
country_pk.netset|287|5278634|23
country_pl.netset|3145|20759970|8
country_ps.netset|103|599300|1
country_pt.netset|443|6457274|7
country_py.netset|69|1099552|1
country_qa.netset|52|831500|3
country_ro.netset|2270|9830672|35
country_rs.netset|304|2285074|20
country_ru.netset|6809|46257206|30
country_sa.netset|378|8693764|15
country_se.netset|2290|30553879|9
country_sg.netset|1340|7383813|7
country_si.netset|438|2805027|7
country_sk.netset|327|2799418|2
country_sr.netset|17|87178|1
country_th.netset|472|9027650|2
country_tn.netset|20|4964736|4
country_tr.netset|769|16457939|8
country_tt.netset|47|526488|1
country_tw.netset|495|35509252|1
country_ua.netset|2858|11855803|9
country_ug.netset|62|313756|1
country_us.netset|20664|1620780943|79
country_uz.netset|69|240128|1
country_vc.netset|61|35837|1
country_vn.netset|367|15756001|7
country_za.netset|1005|28093655|9
country_zm.netset|85|1175992|2
country_zw.netset|61|144896|1

The IPs you posted, in how many days did you collect them?

**Comment by ktsaou** [comment]
The IPs that are matched by all my lists are:

```sh
iprange --merge *.{ip,net}set |\
   iprange --header --compare /tmp/szerver4 - |\
   tr "," "|"
```
name1|name2|ips1|ips2|combined_ips|common_ips
---|---|---|---|---|---|
stdin|/tmp/szerver4|2654632870|803|2654633178|495

**Comment by szepeviktor** [comment]
Oct 18 - Oct 21
My WordPress is very strict.

**Comment by ktsaou** [comment]
Well, it seems there are 308 IPs that are not matched by any of the lists I monitor...

**Comment by szepeviktor** [comment]
Thank very much you for your work!!
I still believe that my WAF irritates botnets.

**Comment by szepeviktor** [comment]
I appreciate your help.
