### ISSUE TITLE
Additional DataPlane.org VNC-based feed

### ISSUE THREAD

**Issue by jtkdpu** [firehol/blocklist-ipsets#30]
One new feed that you may wish to incorporate into the project:

  * [VNC RFB](https://dataplane.org/vncrfb.txt)

Original DataPlane.org family request: #16

**Comment by ktsaou** [comment]
added it.
updating the site.
thanks!

**Comment by ktsaou** [comment]
done. http://iplists.firehol.org/?ipset=dataplane_vncrfb
