### ISSUE TITLE
New Source

### ISSUE THREAD

**Issue by cydave** [firehol/blocklist-ipsets#307]
Hello there, I've recently resumed my honeypot "farm".
As I'm not sure if you (this project) accepts contributions from unknown individuals
I thought I'd let you know that my feed "exists" and can be indexed if desired.

It is located at https://blocklists.0dave.ch/ssh.txt  and is updated daily.

**Comment by cydave** [comment]
ping @ktsaou @alonbl @philwhineray @fawaf @ilyam8 @vlvkobal  :)

**Comment by fawaf** [comment]
@cydave sorry, can't help you here since i do not have access to the repos

**Comment by cydave** [comment]
Nevermind.
