### ISSUE TITLE
127.0.0.1 listed

### ISSUE THREAD

**Issue by lrsaigopal** [firehol/blocklist-ipsets#31]
Hey in this commit : b361dc48ee4db5369c92cd616c8d30ade11c7416 we seem to have blocked 127.0.0.1 .

Can you kindly remove 127.0.0.1 from the list.

**Comment by ktsaou** [comment]
Hi, unfortunately I cannot.

All the lists are provided without any alternation or filtering.

The right way to use these lists is to apply them on the internet interface only. If you do it like that, the private IPs included will not bother you. The opposite actually. Normally you should want to filter 127.0.0.1 or any other private IP on the internet interface.

If you really believe this IP should be filtered out, you should contact the maintainers of the list. For information about the maintainers, check http://iplists.firehol.org/?ipset=blocklist_net_ua

**Comment by lrsaigopal** [comment]
@ktsaou Oh ok. Sure. We have made changes so that we filter out 127.0.0.1 and other private ip ranges.

Thanks @ktsaou .
