### ISSUE TITLE
OpenBL.org is shutting down

### ISSUE THREAD

**Issue by supriyo-biswas** [firehol/blocklist-ipsets#32]
From their twitter:

> Sorry to announce but due to time and financial constraints https://t.co/56UtmZjNni will stop updating end of April and shutdown end of May.

Depending on how things turn out, removing the lists may be necessary.

**Comment by ktsaou** [comment]
Hi,

sad news...

I will not remove them yet. Let's wait for them to really shut down.

**Comment by jonnyt886** [comment]
Getting "OpenBL.org is out of service." for www.openbl.org now

**Comment by ktsaou** [comment]
thanks.
I have removed them already. So, we can close this.
