### ISSUE TITLE
Additional DataPlane.org DNS-based feeds

### ISSUE THREAD

**Issue by jtkdpu** [firehol/blocklist-ipsets#38]
Three new feeds you may wish to incorporate into the project:

  * [DNS recursion desired](https://dataplane.org/dnsrd.txt)
  * [DNS recursion desired IN ANY](https://dataplane.org/dnsrdany.txt)
  * [DNS CH TXT version.bind](https://dataplane.org/dnsversion.txt)

Original DataPlane.org family request: #16

**Comment by ktsaou** [comment]
You rock!
Keep up the good work!

Added them:

- http://iplists.firehol.org/?ipset=dataplane_dnsrd
- http://iplists.firehol.org/?ipset=dataplane_dnsrdany
- http://iplists.firehol.org/?ipset=dataplane_dnsversion
