### ISSUE TITLE
Setting up a blocklist

### ISSUE THREAD

**Issue by szepeviktor** [firehol/blocklist-ipsets#4]
I am thinking about setting up a new blocklist.
My WordPress WAF bans every attacker on the first try.
I've just tested all my 803 IP-s on Wordpress.com's Protect API, 131 are known, but I have to mention that they work with a one hour TTL.

Would you include it here?

**Comment by ktsaou** [comment]
yes of course

**Comment by ktsaou** [comment]
please open a new issue when ready.

**Comment by szepeviktor** [comment]
The solution to my problem is using several blocklists.
https://github.com/szepeviktor/debian-server-tools/blob/master/security/fail2ban-leanmail/leanmail.sh
