### ISSUE TITLE
Why are there bitcoin nodes in these lists?

### ISSUE THREAD

**Issue by ilsawa** [firehol/blocklist-ipsets#41]
You have lists of bitcoin nodes in blocklist-ipsets.
Do you think that they should be blocked?
How do they relate to cybercrime? According to the description in README.md, just such are listed here.

**Comment by 5967158** [comment]
Dear firehol Dev.
My bitcoin node in blocklist-ipsets too.
Who gave you the right to accuse me of cyber-crime?

**Comment by ktsaou** [comment]
Hi,

the primary reason of the site is to document how the various lists relate to each other.
If you check the bitcoin lists are under the `organizations` category:

![screenshot from 2017-07-24 00-15-07](https://user-images.githubusercontent.com/2662304/28502921-32b15130-7005-11e7-83ab-303cd574d211.png)

This category has nothing to do with cybercrime. It just lists various organizations that could be interesting to compare with cybercrime IP lists.

This comparison is made here:

http://iplists.firehol.org/?ipset=bitcoin_nodes

![screenshot from 2017-07-24 00-17-46](https://user-images.githubusercontent.com/2662304/28502934-9a2e3210-7005-11e7-8e31-b2bcffc034ed.png)

The finding here is that `pushing_inertia` matches 24% of bitcoin nodes, `tor` matches just 1.6% of bitcoin nodes, and cybercrime related lists (attacks, malware, etc) match a tiny percentage.

Actually the fact that the bitcoin nodes are not matched by cybercrime should work the other way around. We have proof bitcoin nodes are not participating in cybercrime.

I understand you are offended by the presentation layer of this analysis. I would be glad to help, by making adjustments to this presentation, following your suggestions.

**Comment by unamis76** [comment]
The issue isn't the categorization, but the fact that you made a blacklist with known Bitcoin nodes. I am aware that these black-lists are opt-in, but I think the community would still like to know why you have such a list.

**Comment by ktsaou** [comment]
Well, I didn't make it. I don't "make" lists. I only "use" what is already available.

I thought this is clear:

https://github.com/firehol/blocklist-ipsets/blob/master/bitcoin_nodes.ipset

```
# [BitNodes] (https://getaddr.bitnodes.io/) Bitcoin connected 
# nodes, globally.
#
# Maintainer      : BitNodes
# Maintainer URL  : https://getaddr.bitnodes.io/
# List source URL : https://getaddr.bitnodes.io/api/v1/snapshots/latest/
# Source File Date: Sun Jul 23 23:08:12 UTC 2017
#
# Category        : organizations
```

In this repo there is the entire IPv4 address space. If you search with a tool that can match IPs in subnets, you will find every single IP. The list it is found is important, not its inclusion in the repo.

**Comment by unamis76** [comment]
There are no lists that I know of except these. But fair enough for me, thank you.
