### ISSUE TITLE
[trustedsec_atif]: url change

### ISSUE THREAD

**Issue by kjake** [firehol/blocklist-ipsets#47]
source file is no longer at https://www.trustedsec.com/banlist.txt, moved to https://www.binarydefense.com/banlist.txt

**Comment by ktsaou** [comment]
hm... we already have that URL:

```

# -----------------------------------------------------------------------------
# BinaryDefense.com

update bds_atif $[24*60] 0 ipv4 ip \
	"https://www.binarydefense.com/banlist.txt" \
	remove_comments \
	"reputation" \
	"Artillery Threat Intelligence Feed and Banlist Feed" \
	"Binary Defense Systems" "https://www.binarydefense.com/"


# -----------------------------------------------------------------------------
# TrustedSec.com

update trustedsec_atif $[24*60] 0 ipv4 ip \
	"https://www.trustedsec.com/banlist.txt" \
	remove_comments \
	"reputation" \
	"Artillery Threat Intelligence Feed and Banlist Feed" \
	"TrustedSec" "https://www.trustedsec.com/"

```

So, remove trustedsec.com?

**Comment by kjake** [comment]
Whoops, missed that you had the BDS already.  If you check, you'll notice that the trustedsec_atif url doesn't work any more.  Both companies are run by Dave Kennedy, but BDS has been setup as an offshoot to focus on MSSP type things leaving Trusted Sec to focus on pen testing and consultancy.
