### ISSUE TITLE
Blocking AWS

### ISSUE THREAD

**Issue by Naurhir** [firehol/blocklist-ipsets#48]
I noticed today that Firehol level 3 was blocking a large grouping of AWS ip addresses.

For example:
54.81.100.98-54.81.100.98
54.81.122.6-54.81.122.6
54.81.158.0-54.81.158.255
54.81.168.0-54.81.168.255
54.81.171.0-54.81.171.255 

I am concerned that legitimate business may be impacted by blocking subsets of these ip addresses.

**Comment by ktsaou** [comment]
Let me check:

```sh
# cat /tmp/ips 
54.81.100.98-54.81.100.98
54.81.122.6-54.81.122.6
54.81.158.0-54.81.158.255
54.81.168.0-54.81.168.255
54.81.171.0-54.81.171.255

# cat /tmp/ips | iprange - --compare-next *.{ip,net}set | grep -v ',0$'
stdin,pushing_inertia_blocklist.netset,5,878,770,34512264,34512264,770
stdin,iblocklist_level3.netset,5,17801,770,139013335,139013335,770
stdin,ib_bluetack_level3.netset,5,17801,770,139013335,139013335,770
stdin,firehol_webserver.netset,5,3875,770,34676267,34676267,770
stdin,firehol_webclient.netset,5,4214,770,4292,5061,1
stdin,firehol_level3.netset,5,26830,770,118248,118248,770
stdin,dronebl_anonymizers.netset,5,698333,770,729958,730727,1
stdin,dragon_http.netset,5,219,770,59136,59138,768
stdin,sslbl_aggressive.ipset,5,3318,770,3318,4087,1
stdin,myip.ipset,5,3083,770,3083,3852,1
```

`firehol_level3` includes `pushing_inertia`, so they have the exact match.

In general, `firehol_level3` is like defcon. If you reach level 3, you should expect some false positives to be included. Most people should stay at `firehol_level1` and include `firehol_level2` and `firehol_level3` only when they have reason to.
