### ISSUE TITLE
stopforumspam: do not block IPs with low number of incidents

### ISSUE THREAD

**Issue by slrslr** [firehol/blocklist-ipsets#49]
Hello,

does stopforumspam provide any way to get only IPs with lets say more than 2-3 incidents in last 90 days? Or other way exclude low risk IPs from the DB? I know i can reduce risks by using 1day or 7 day blocklist, but banning based on number of incidents in time period would be much more accurate for me.

I had to disable whole SFS blocklist because this was customer of mine who was blocked: https://www.stopforumspam.com/evidence/157095723, the IP looks quite innocent in my oppinion and it is probably shared IP and in higher risk location, but it blocked the customer and i do not want this to happen again.

**Comment by ktsaou** [comment]
Hi,

stopforumspam provides a [toxic list](http://iplists.firehol.org/?ipset=stopforumspam_toxic).

If this is not good for you, I suggest to discuss this issue with stopforumspam, since I cannot really know the reasons of listing.
