### ISSUE TITLE
Beer Money

### ISSUE THREAD

**Issue by rhyselsmore** [firehol/blocklist-ipsets#5]
I know that this project is an aggregation of other people's intelligence, but I still want to sling you some beer money for your excellent work with this.

How would one go about doing that?

**Comment by ktsaou** [comment]
Thanks! I am glad you like it!

I am still trying to figure out the next step for leveraging all this intelligence to improve our security...

Instead of giving me money, can you help this cause in any way?
(don't ask me how, I haven't figured it out yet)

**Comment by rhyselsmore** [comment]
I can sure lend some of my time to help out however needed. this is an area that interests me greatly. Thanks for getting back to me, and if you think of anything I can help with, let me know. I will do the same.

**Comment by ktsaou** [comment]
Well, I am closing this. I you come with any ideas, please open a new one.
