### ISSUE TITLE
[info] Referencement of firehol_level1.netset

### ISSUE THREAD

**Issue by funilrys** [firehol/blocklist-ipsets#56]
Hello @ktsaou  ,

Because I want to be transparent, I just wanted to inform you that we added `firehol_level1.netset` file to [Ultimate.Hosts.Blacklist](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist) through [Ultimate-Hosts-Blacklist/firehol_level1](https://github.com/Ultimate-Hosts-Blacklist/firehol_level1).

Cheers,
Nissar

P.S: Feel free to close/comment after reading this information.

**Comment by ktsaou** [comment]
nice! thank you for letting me know...
