### ISSUE TITLE
Git pull not working, how to update regularly?

### ISSUE THREAD

**Issue by mlodic** [firehol/blocklist-ipsets#62]
Hi, thank you in advance for the work you have done.

I was trying to use the blocklists on this repo and to update them regularly.

I followed the instructions on the docs and I thought that it would have been enough to `git pull` to update my local IP database.

However, I noticed that it broke the repo, forcing me to destroy my local repository and to `git clone` again. (I did no local commits at all, just `git pull`)
`Your branch and 'origin/master' have diverged,
and have 1 and 1 different commit each, respectively.
  (use "git pull" to merge the remote branch into yours)
You have unmerged paths.
  (fix conflicts and run "git commit")
`

Do you have any suggestions to update the blocklists in a simple and regular manner as `git pull` would have provided?

Thank you

**Comment by ktsaou** [comment]
Hi, due to the large changes made, github made this repo permanently detatched from clones and forks. Also, there is no history logged in the repo. We actually push a new fresh repo, once per day.

So, just clone it every time.

**Comment by mlodic** [comment]
Ok, I thought that maybe there was an easier way than download ~150M every time.

Thank you, I'll close the issue.
