### ISSUE TITLE
False entries in firehol_level3.netset

### ISSUE THREAD

**Issue by krischeu** [firehol/blocklist-ipsets#66]
Hi,
I am using pfsense with plugin pfBlockerNG. There are very much normal website, which are not working anymore, because the list points to a subnet 217.160.0.0/24. It would be great, if this will only point to the direct ip addresses.

Who is maintaining the list and who can be reached for asking for a solution?
# Maintainer      : FireHOL
# Maintainer URL  : http://iplists.firehol.org/
https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level3.netset

Best Regards,

Heinz Krischeu

**Comment by pielgrzym** [comment]
Ran into similar problem - this list blocks bitbucket.org (104.192.143.1 104.192.143.2).

**Comment by krischeu** [comment]
I am using pfsense and solved it with white list.
