### ISSUE TITLE
Jigsaw Security IP Sources

### ISSUE THREAD

**Issue by jigsawsecurity** [firehol/blocklist-ipsets#7]
A list with malicious IP sources

http://www.slcsecurity.com/feedspublic/IP/malicious-ip-dst.txt
http://www.slcsecurity.com/feedspublic/IP/malicious-ip-src.txt

**Comment by ktsaou** [comment]
Thanks!
I guess I will take content from this here: http://www.jigsawsecurityenterprise.com/#!open-blacklist/kafsx

I'll need a few days to add them to the site. I have done various updates on the programs involved and I need to test them before using the new ones for updating the site.

Thanks again!

**Comment by ktsaou** [comment]
I have assumed these lists are updated daily.
I'll push the site update later today.

**Comment by ktsaou** [comment]
Added them:

http://iplists.firehol.org/?ipset=jigsaw_attacks
http://iplists.firehol.org/?ipset=jigsaw_malware

If all is ok, please close this ticket.

Thanks!
